version: '3'
services:
  dev-db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=web
      - POSTGRES_PASSWORD=superrahasia
      - POSTGRES_DB=nest
    networks:
      - nest
  test-db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=web
      - POSTGRES_PASSWORD=superrahasia
      - POSTGRES_DB=nest
    networks:
      - nest
networks:
  nest: